### ISSUE TITLE
JsonException when calling GetStorageStatusDataByPlant

### ISSUE THREAD

**Issue by PsilocFinch** [ealse/GrowattApi#9]
var storageStatusData = await session.GetStorageStatusDataByPlant(plant.Id, device.SerialNumber);

Falls over with:

System.Text.Json.JsonException: 'The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.'

**Comment by PsilocFinch** [comment]
I think it's the RelativeUrl class. It looks to me like Growatt have changed the names of some of the endpoints?

e.g. getStorageTotalData looks to have been renamed to getSPATotalData

**Comment by ealse** [comment]
Hi PsilocFinch,
The Growatt SPA seems to be another device than the growatt storage products. That also explains why the relative url is different.
It's hard for me to collect all the data because the traffic is mimicked to their own web application and I don't own all the devices.
But feel free to add the SPA and offer it as a pull request or use this project as an example.

**Comment by PsilocFinch** [comment]
Ah, I thought a Growatt update had broken it, but now you mention it my device model number does have "SPA" in it, so I guess my device must access a different web service.

No worries, I can work with it as raw JSON.

I'm a bit of a novice at this, but would it not be possible to make this stuff overridable so we can change those relative URLs and some of the JsonPropertyNames in the models without needing an update?

In any case thanks for writing a great extension.

**Comment by ealse** [comment]
The relative urls can already be overwritten, but the other data indeed cannot. But I have released a few minutes ago a new version of the package (1.2.1) where accessibility of the methods `GetPostResponseData` and `GetResponseData` are changed. Now you can more easily use your own models in combination with this package.

And yes the packages could of course have a more generic setup, but then you also have still to provide your own models etc. And to be completely honest, if you already have that, you have almost made the entire package yourself. Because the package does not contain that much logic. The main advantage of the package is that you and others do not have to create the models yourself and that you can see how the connections work.
So if you have made the models and would like to share them, feel free to submit a pull request.

Just some code to give you a idea:

    var content = new FormUrlEncodedContent([new KeyValuePair<string, string>("spaSn", device.SerialNumber)]);
    var data = await session.GetPostResponseData<YOURMODEL>(content, new Uri($"session.GrowattApiBaseUrl}panel/spa/getSPATotalData?plantId={plant.Id}"), "obj.datas");

**Comment by PsilocFinch** [comment]
To be honest I didn't fix the models, I just ditched them and started parsing the response as basic JSON objects and then accessing values by JSON property name in my project.

I wonder if a simple resolution would be to add a property for each of the models which just offers the raw JSON from the server? That way it is always possible to access the data manually if the model fails to map the JSON to a property.

**Comment by allanpoulsen** [comment]
I look into the same issue. I've edited the URI to receive storage JSON data. I have replaced the JSON objects in the project with the model that my equipment returns. The JSON objects are VERY different.
